site_name: "Scholingsaanbod AI voor Artsen"

nav:
  - Home: index.md
  - Overzicht: SCHOLINGSAANBOD.md
  - Bijdragen: bijdragen.md
  - Status: status.md

theme:
  name: lumen         # ← Bootswatch-thema
  logo: images/logo.png
  favicon: images/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search
  - tags

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - css/extra.css

extra_javascript:
  - js/filter.js
