# mkdocs.yml

site_name: "Scholingsaanbod AI voor Artsen"
repo_url: https://github.com/your-org/ai-education-voor-artsen
edit_uri: edit/main

nav:
  - Home: index.md
  - Cursussen:
      - Overzicht: SCHOLINGSAANBOD.md

theme:
  name: lumen
  logo: images/logo.png
  favicon: images/favicon.ico

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.snippets

extension_configs:
  pymdownx.snippets:
    base_path: docs

extra_css:
  - css/extra.css
