site_name: "AI Scholingsaanbod voor Clinici"
site_url: https://ajsvdk.github.io/Ai-Geletterdheid-FMS/

nav:
  - Home: index.md
  - Scholingsaanbod: scholingsaanbod.md
  - Bijdragen: bijdragen.md
  - Over: over.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Naar donkere modus
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Naar lichte modus
  language: nl

plugins:
  - search:
      lang: nl

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ajsvdk/Ai-Geletterdheid-FMS

extra_css:
  - css/extra.css

extra_javascript:
  - js/filter.js
