name: Build and Deploy MkDocs site

# Run op push naar main
on:
  push:
    branches:
      - main

# Zet expliciet rechten zodat Pages mag deployen
permissions:
  contents: read        # nodig voor checkout
  pages: write          # nodig om Pages te updaten
  id-token: write       # nodig voor configure-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. checkout
      - uses: actions/checkout@v3

      # 2. installeer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. installeer mkdocs + Material
      - name: Install dependencies
        run: |
          pip install mkdocs-material

      # 4. bouw de site
      - name: Build MkDocs site
        run: |
          mkdocs build

      # 5. upload het site‑artifact voor deploy
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 6. configureer Pages
      - uses: actions/configure-pages@v3

      # 7. deploy
      - uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
