name: Build and Deploy MkDocs site

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-bootswatch pymdown-extensions

      - name: Build MkDocs site
        run: |
          mkdocs build

      # ──────────────────────────────────────────────────────────────
      # Vervang placeholder __ISSUE_TOKEN__ door geheime ISSUE_TOKEN
      # ──────────────────────────────────────────────────────────────
      - name: Inject issue token in built HTML
        env:
          TOKEN: ${{ secrets.ISSUE_TOKEN }}
        run: |
          if [ -z "$TOKEN" ]; then
            echo "::error::ISSUE_TOKEN secret ontbreekt"; exit 1;
          fi
          find site -type f -name '*.html' -exec \
            sed -i "s/__ISSUE_TOKEN__/${TOKEN}/g" {} +

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
        with:
          enablement: 'workflow'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
